=== apache/camel/components/camel-linkedin/camel-linkedin-api/src/main/resources/wadl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://wadl.dev.java.net/2009/02"
  xmlns:tns="http://wadl.dev.java.net/2009/02"
  xmlns:xml="http://www.w3.org/XML/1998/namespace"
  elementFormDefault="qualified">

  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
    schemaLocation="http://www.w3.org/2001/xml.xsd"/>

  <xs:element name="application">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:grammars" minOccurs="0"/>
        <xs:element ref="tns:resources" minOccurs="0"
          maxOccurs="unbounded"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="tns:resource_type"/>
          <xs:element ref="tns:method"/>
          <xs:element ref="tns:representation"/>
          <xs:element ref="tns:param"/>
        </xs:choice>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="doc">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="title" type="xs:string"/>
      <xs:attribute ref="xml:lang"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="grammars">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="tns:include"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:resource" maxOccurs="unbounded"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="base" type="xs:anyURI"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="resource">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:param" minOccurs="0" maxOccurs="unbounded"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="tns:method"/>
          <xs:element ref="tns:resource"/>
        </xs:choice>
        <xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other"
          processContents="lax"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="type" type="tns:resource_type_list"/>
      <xs:attribute name="queryType" type="xs:string"
        default="application/x-www-form-urlencoded"/>
      <xs:attribute name="path" type="xs:string"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="resource_type_list">
    <xs:list itemType="xs:anyURI"/>
  </xs:simpleType>

  <xs:element name="resource_type">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:param" minOccurs="0" maxOccurs="unbounded"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="tns:method"/>
          <xs:element ref="tns:resource"/>
        </xs:choice>
        <xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other"
          processContents="lax"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="method">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:request" minOccurs="0"/>
        <xs:element ref="tns:response" minOccurs="0"
          maxOccurs="unbounded"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="name" type="tns:Method"/>
      <xs:attribute name="href" type="xs:anyURI"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="Method">
    <xs:union memberTypes="tns:HTTPMethods xs:NMTOKEN"/>
  </xs:simpleType>

  <xs:simpleType name="HTTPMethods">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="GET"/>
      <xs:enumeration value="POST"/>
      <xs:enumeration value="PUT"/>
      <xs:enumeration value="HEAD"/>
      <xs:enumeration value="DELETE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="include">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="href" type="xs:anyURI"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="request">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:param" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:representation" minOccurs="0"
          maxOccurs="unbounded"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="response">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:param" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:representation" minOccurs="0"
          maxOccurs="unbounded"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="status" type="tns:statusCodeList"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="uriList">
    <xs:list itemType="xs:anyURI"/>
  </xs:simpleType>

  <xs:element name="representation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:param" minOccurs="0" maxOccurs="unbounded"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="element" type="xs:QName"/>
      <xs:attribute name="mediaType" type="xs:string"/>
      <xs:attribute name="href" type="xs:anyURI"/>
      <xs:attribute name="profile" type="tns:uriList"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="statusCodeList">
    <xs:list itemType="xs:unsignedInt"/>
  </xs:simpleType>

  <xs:simpleType name="ParamStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="plain"/>
      <xs:enumeration value="query"/>
      <xs:enumeration value="matrix"/>
      <xs:enumeration value="header"/>
      <xs:enumeration value="template"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="param">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:option" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:link" minOccurs="0"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="href" type="xs:anyURI"/>
      <xs:attribute name="name" type="xs:NMTOKEN"/>
      <xs:attribute name="style" type="tns:ParamStyle"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="type" type="xs:QName" default="xs:string"/>
      <xs:attribute name="default" type="xs:string"/>
      <xs:attribute name="required" type="xs:boolean" default="false"/>
      <xs:attribute name="repeating" type="xs:boolean" default="false"/>
      <xs:attribute name="fixed" type="xs:string"/>
      <xs:attribute name="path" type="xs:string"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="option">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="value" type="xs:string" use="required"/>
      <xs:attribute name="mediaType" type="xs:string"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="link">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:doc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="resource_type" type="xs:anyURI"/>
      <xs:attribute name="rel" type="xs:token"/>
      <xs:attribute name="rev" type="xs:token"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== apache/camel/components/camel-linkedin/camel-linkedin-api/src/main/resources/linkedin-api-wadl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<wadl:application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:wadl="http://wadl.dev.java.net/2009/02"
                  xmlns:tns="http://camel.apache.org/component/linkedin/api/model"
                  xsi:schemaLocation="http://camel.apache.org/component/linkedin/api/model linkedin-api-schema.xsd
                  http://wadl.dev.java.net/2009/02 http://www.w3.org/Submission/wadl/wadl.xsd">

  <wadl:grammars>
    <wadl:include href="linkedin-api-schema.xsd"/>
  </wadl:grammars>

  <wadl:resources base="http://api.linkedin.com/v1/">

    <!-- People -->
    <wadl:resource path="people" id="People">

      <wadl:resource path="~{fields}">
        <wadl:doc><![CDATA[https://developer-programs.linkedin.com/documents/profile-api]]></wadl:doc>
        <wadl:method name="GET" id="getPerson">
          <wadl:request>
            <wadl:param href="#fields-selector"/>
            <wadl:param href="#secure-urls"/>
          </wadl:request>
          <wadl:response>
            <wadl:representation href="#person"/>
          </wadl:response>
        </wadl:method>

      </wadl:resource>

      <wadl:resource path="~/connections{fields}">
        <wadl:doc><![CDATA[https://developer-programs.linkedin.com/documents/connections-api]]></wadl:doc>
        <wadl:method name="GET" id="getConnections">
          <wadl:request>
            <wadl:param href="#fields-selector"/>
            <wadl:param href="#secure-urls"/>
          </wadl:request>
          <wadl:response>
            <wadl:representation href="#connections"/>
          </wadl:response>
        </wadl:method>
      </wadl:resource>

      <wadl:resource path="~/shares">
        <wadl:method name="POST" id="share">
          <wadl:request>
            <wadl:representation mediaType="application/xml" element="tns:share"/>
          </wadl:request>
          <wadl:response>
            <wadl:representation mediaType="application/xml" element="tns:update"/>
          </wadl:response>
        </wadl:method>
      </wadl:resource>

      <wadl:resource path="~/network">
        <wadl:doc><![CDATA[https://developer-programs.linkedin.com/documents/get-network-updates-and-statistics-api]]></wadl:doc>

        <wadl:resource path="updates{fields}">
          <wadl:param href="#scope"/>
          <wadl:param href="#type"/>
          <wadl:param href="#count"/>
          <wadl:param href="#start"/>
          <wadl:param href="#after"/>
          <wadl:param href="#before"/>
          <wadl:param href="#show-hidden-members"/>

          <wadl:method name="GET" id="getNetworkUpdates">
            <wadl:request>
              <wadl:param href="#fields-selector"/>
              <wadl:param href="#secure-urls"/>
            </wadl:request>
            <wadl:response>
              <wadl:representation href="#updates"/>
            </wadl:response>
          </wadl:method>
        </wadl:resource>

        <wadl:resource path="updates/key={update-key}">
          <wadl:resource path="update-comments{fields}">
            <wadl:method name="GET" id="getUpdateComments">
              <wadl:request>
                <wadl:param href="#update-key"/>
                <wadl:param href="#fields-selector"/>
                <wadl:param href="#secure-urls"/>
              </wadl:request>
              <wadl:response>
                <wadl:representation href="#update-comments"/>
              </wadl:response>
            </wadl:method>
          </wadl:resource>

          <wadl:resource path="update-comments">
            <wadl:method name="POST" id="addUpdateComment">
              <wadl:request>
                <wadl:param href="#update-key"/>
                <wadl:representation mediaType="application/xml" element="tns:updatecomment"/>
              </wadl:request>
            </wadl:method>
          </wadl:resource>

          <wadl:resource path="likes{fields}">
            <wadl:method name="GET" id="getUpdateLikes">
              <wadl:request>
                <wadl:param href="#update-key"/>
                <wadl:param href="#fields-selector"/>
                <wadl:param href="#secure-urls"/>
              </wadl:request>
              <wadl:response>
                <wadl:representation mediaType="application/xml" element="tns:likes"/>
              </wadl:response>
            </wadl:method>
          </wadl:resource>

          <wadl:resource path="is-liked">
            <wadl:method name="PUT" id="likeUpdate">
              <wadl:request>
                <wadl:param href="#update-key"/>
                <wadl:representation href="#is-liked"/>
              </wadl:request>
            </wadl:method>
          </wadl:resource>

        </wadl:resource>

        <wadl:resource path="network-stats">
          <wadl:method name="GET" id="getNetworkStats">
            <wadl:response>
              <wadl:representation mediaType="application/xml" element="tns:networkstats"/>
            </wadl:response>
          </wadl:method>
        </wadl:resource>

      </wadl:resource>

      <wadl:resource path="~/person-activities">
        <wadl:method name="POST" id="addActivity">
          <wadl:request>
            <wadl:representation mediaType="application/xml" element="tns:activity"/>
          </wadl:request>
        </wadl:method>
      </wadl:resource>

      <wadl:resource path="~/mailbox">
        <wadl:doc><![CDATA[https://developer-programs.linkedin.com/documents/invitation-api]]></wadl:doc>
        <wadl:method name="POST" id="addInvite">
          <wadl:request>
            <wadl:representation mediaType="application/xml" element="tns:mailboxitem"/>
          </wadl:request>
        </wadl:method>
      </wadl:resource>

      <wadl:resource path="~/group-memberships{fields}">
        <wadl:param name="membership-state" style="query" type="tns:membershipstatecode"/>
        <wadl:param href="#fields-selector"/>
        <wadl:method name="GET" id="getGroupMemberships">
          <wadl:request>
            <wadl:param href="#count"/>
            <wadl:param href="#start"/>
          </wadl:request>
          <wadl:response>
            <wadl:representation href="#groupmemberships"/>
          </wadl:response>
        </wadl:method>
      </wadl:resource>

      <wadl:resource path="~/group-memberships">
        <wadl:method name="POST" id="addGroupMembership">
          <wadl:request>
            <wadl:representation href="#groupmembership"/>
          </wadl:request>
        </wadl:method>
      </wadl:resource>

      <wadl:resource path="~/group-memberships/{group-id}{fields}">
        <wadl:method name="GET" id="getGroupMembershipSettings">
          <wadl:request>
            <wadl:param href="#group-id"/>
            <wadl:param href="#fields-selector"/>
          </wadl:request>
          <wadl:response>
            <wadl:representation href="#groupmembership"/>
          </wadl:response>
        </wadl:method>
      </wadl:resource>

      <wadl:resource path="~/group-memberships/{group-id}">
        <wadl:method name="PUT" id="updateGroupMembership">
          <wadl:request>
            <wadl:param href="#group-id"/>
            <wadl:representation href="#groupmembership"/>
          </wadl:request>
        </wadl:method>

        <wadl:method name="DELETE" id="removeGroupMembership">
          <wadl:request>
            <wadl:param href="#group-id"/>
          </wadl:request>
        </wadl:method>

        <wadl:resource path="posts{fields}">
          <wadl:method name="GET" id="getPosts">
            <wadl:request>
              <wadl:param href="#group-id"/>
              <wadl:param href="#start"/>
              <wadl:param href="#count"/>
              <wadl:param href="#order"/>
              <wadl:param href="#post-role"/>
              <wadl:param href="#category"/>
              <wadl:param href="#modified-since"/>
              <wadl:param href="#fields-selector"/>
            </wadl:request>
            <wadl:response>
              <wadl:representation href="#posts"/>
            </wadl:response>
          </wadl:method>
        </wadl:resource>

      </wadl:resource>

      <wadl:resource path="~/job-bookmarks">

        <wadl:method name="GET" id="getJobBookmarks">
          <wadl:response>
            <wadl:representation href="#job-bookmarks"/>
          </wadl:response>
        </wadl:method>

        <wadl:method name="POST" id="addJobBookmark">
          <wadl:request>
            <wadl:representation href="#job-bookmark"/>
          </wadl:request>
        </wadl:method>

        <wadl:resource path="{job-id}">
          <wadl:method name="DELETE" id="removeJobBookmark">
            <wadl:request>
              <wadl:param href="#job-id"/>
            </wadl:request>
          </wadl:method>
        </wadl:resource>
      </wadl:resource>

      <wadl:resource path="~/suggestions">

        <wadl:resource path="groups{fields}">
          <wadl:method name="GET" id="getSuggestedGroups">
            <wadl:request>
              <wadl:param href="#fields-selector"/>
            </wadl:request>
